# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: jublia_email_autosend
    build: .
    command: jublia_email_autosend run -h 0.0.0.0
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/jublia_email_autosend.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
    volumes:
      - ./jublia_email_autosend:/code/jublia_email_autosend
      - ./db/:/db/
    ports:
      - "5000:5000"
  rabbitmq:
    image: rabbitmq
  redis:
    image: redis
  celery:
    image: jublia_email_autosend
    command: "celery worker -A jublia_email_autosend.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
      - CELERY_RESULT_BACKEND_URL=redis://redis
